export const ACTIONS = {
  INIT: "INIT",
  EDIT: "EDIT",
  ADD: "ADD",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  SELECT: "SELECT",
  TOGGLE_FROM_SELECTED: "TOGGLE_FROM_SELECTED",
  MARK_COMPLETED: "MARK_COMPLETED",
  ALTER_COMPLETION_IN_BULK: "ALTER_COMPLETION_IN_BULK",
  DELETE_IN_BULK: "DELETE_IN_BULK",
  RESET: "RESET",
  RESET_SELECTED_IDS: "RESET_SELECTED_IDS",
};

export const BULK_ACTIONS = {
  TOGGLE_COMPLETION: "Toggle completion",
  CLEAR_SELECTION: "Clear selection",
  DELETE: "Delete",
};

export const EDIT_WINDOW_ACTIONS = {
  SHOW: "SHOW",
  CLOSE: "CLOSE",
  UPDATE_DATA: "UPDATE_DATA",
};

export const CATEGORIES = {
  PERSONAL: "personal",
  ACADEMIC: "academic",
  SOCIAL: "social",
};
export const URGENCIES = {
  LOW: "low",
  MEDIUM: "medium",
  HIGH: "high",
};
export const CATEGORY_ICON_CLASS = {
  USERALT: "fa-user",
  BOOKOPEN: "fa-book",
  USERS: "fa-users",
};

export const COLOR = {
  GREEN: "cgreen",
  YELLOW: "cyellow",
  RED: "cred",
};

export const URGENCY_TO_COLOR_MAP = {
  [URGENCIES.LOW]: COLOR.GREEN,
  [URGENCIES.MEDIUM]: COLOR.YELLOW,
  [URGENCIES.HIGH]: COLOR.RED,
};
export const CATEGORY_TO_ICON_CLASS_MAP = {
  [CATEGORIES.PERSONAL]: CATEGORY_ICON_CLASS.USERALT,
  [CATEGORIES.ACADEMIC]: CATEGORY_ICON_CLASS.BOOKOPEN,
  [CATEGORIES.SOCIAL]: CATEGORY_ICON_CLASS.USERS,
};

export const TODO_FORM_INPUTS = {
  TITLE: "Title",
  URGENCY: "Urgency",
  CATEGORY: "Category",
};

export const FILTER_ACTIONS = {
  UPDATE_URGENCY_FILTER: "UPDATE_URGENCY_FILTER",
  UPDATE_CATEGORY_FILTER: "UPDATE_CATEGORY_FILTER",
  TOGGLE_INCOMPLETE_ENABLED: "TOGGLE_INCOMPLETE_ENABLED",
  UPDATE_SEARCH_VALUE: "UPDATE_SEARCH_VALUE",
};

export const INVALID_POSITION = -1;
